---
language: c
compiler:
  - clang
  - gcc
os:
  - linux
  - osx

before_install:
  - pip install --user cpp-coveralls
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update && brew install lcov; fi
script:
  - cp travis-local.mk local.mk
  - make test
after_success:
  - coveralls --gcov-options '\-lp' $(for d in * */t; do printf " -i $d"; done)
